version: "3" 
services:
  cms-frontend:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: cms-frontend
    ports:
      - "3000:3000" 
    env_file:
      - .env

